<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Kirin_Tool</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <Product>Kirin Tool for Linux</Product>
    <Version>2.4.2</Version>
    <FileVersion>2.4.2</FileVersion>
    <InformationalVersion>2.4.2</InformationalVersion>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
    <Content Include="fastboot/payload">
      <Link>fastboot/payload</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="loaders/**/*">
      <Link>loaders/%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.3" />
    <PackageReference Include="BouncyCastle.NetCore" Version="2.2.1" />
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Obfuscar" Version="2.2.50">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Management" Version="9.0.7" />
    <PackageReference Include="System.IO.Ports" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Avalonia" />
    <Using Include="Avalonia.Controls" />
    <Using Include="Avalonia.Threading" />
  </ItemGroup>

</Project>
